package api

// EnglishMessages сатрҳои интерфейс барои забони англисӣ
var EnglishMessages = map[string]string{
	"welcome":            "👋 Welcome to *AnimeBot*!\n\nPlease choose your language:",
	"welcome_back":       "👋 Welcome back, %s!\n\nWhat would you like to do?",
	"language_set":       "✅ Language set to English!",
	"main_menu":          "What would you like to do?",
	"btn_search":         "🔍 Search Anime",
	"btn_random":         "🎲 Random Anime",
	"btn_top":            "🏆 Top Anime",
	"btn_settings":       "⚙️ Settings",
	"btn_help":           "❓ Help",
	"ask_search_query":   "🔍 Send me the anime name you want to search for:",
	"searching":          "🔎 Searching for \"%s\"...",
	"no_results":         "😔 No anime found for \"%s\". Try another name.",
	"search_results":     "🔍 Results for \"%s\":",
	"loading_anime":      "⏳ Loading anime details...",
	"anime_not_found":    "😔 Anime not found.",
	"episodes_title":     "📺 Episodes for *%s*",
	"no_episodes":        "No episode data available yet.",
	"btn_episodes":       "📺 Episodes",
	"btn_open_mal":       "🔗 Open on MyAnimeList",
	"btn_back":           "⬅️ Back",
	"btn_back_to_menu":   "⬅️ Back to menu",
	"settings_title":     "⚙️ *Settings*\n\nCurrent language: %s",
	"btn_change_lang":    "🌐 Change Language",
	"help_text":          "🤖 *AnimeBot Help*\n\nSend any anime name to search, or use the menu buttons below.\n\nCommands:\n/start - restart the bot\n/search <name> - search anime\n/random - get a random anime\n/top - top anime list\n/settings - change language\n/help - show this message",
	"error_generic":      "⚠️ Something went wrong. Please try again later.",
	"score_label":        "⭐ Score",
	"episodes_label":     "📺 Episodes",
	"status_label":       "📌 Status",
	"type_label":         "🎞 Type",
	"year_label":         "📅 Year",
	"genres_label":       "🏷 Genres",
	"top_title":          "🏆 Top Anime Right Now",
	"random_loading":     "🎲 Picking a random anime for you...",
}
