package api

// EnglishMessages сатрҳои интерфейс барои забони англисӣ
var EnglishMessages = map[string]string{
	"welcome":           "👋 Welcome to *AnimeBot*!\n\nPlease choose your language:",
	"welcome_back":      "👋 Welcome back, %s!\n\nWhat would you like to do?",
	"language_set":      "✅ Language set to English!",
	"main_menu":         "What would you like to do?",
	"btn_search":        "🔍 Search Anime",
	"btn_random":        "🎲 Random Anime",
	"btn_mood":          "🎭 Suggest by Mood",
	"btn_top":           "🏆 Top Anime",
	"btn_settings":      "⚙️ Settings",
	"btn_help":          "❓ Help",
	"ask_search_query":  "🔍 Send me the anime name you want to search for:",
	"searching":         "🔎 Searching for \"%s\"...",
	"no_results":        "😔 No anime found for \"%s\". Try another name.",
	"search_results":    "🔍 Results for \"%s\":",
	"loading_anime":     "⏳ Loading anime details...",
	"anime_not_found":   "😔 Anime not found.",
	"episodes_title":    "📺 Episodes for *%s*",
	"no_episodes":       "No episode data available yet.",
	"btn_episodes":      "📺 Episodes",
	"btn_open_mal":      "🔗 Open on MyAnimeList",
	"btn_back":          "⬅️ Back",
	"btn_back_to_menu":  "⬅️ Back to menu",
	"settings_title":    "⚙️ *Settings*\n\nCurrent language: %s",
	"btn_change_lang":   "🌐 Change Language",
	"help_text":         "🤖 *AnimeBot Help*\n\nSend any anime name to search, or use the menu buttons below.\n\nCommands:\n/start - restart the bot\n/search <name> - search anime\n/random - get a random anime\n/top - top anime list\n/settings - change language\n/help - show this message",
	"error_generic":     "⚠️ Something went wrong. Please try again later.",
	"score_label":       "⭐ Score",
	"episodes_label":    "📺 Episodes",
	"status_label":      "📌 Status",
	"type_label":        "🎞 Type",
	"year_label":        "📅 Year",
	"genres_label":      "🏷 Genres",
	"top_title":         "🏆 Top Anime Right Now",
	"random_loading":    "🎲 Picking a random anime for you...",
	"ask_mood":          "🎭 Tell me what mood you're in — e.g. \"romance\", \"funny\", \"scary\", \"action\", \"sad\"... write it in your own words, I'll figure it out 😉",
	"mood_searching":    "🎭 Looking for something that fits your mood...",
	"mood_result_intro": "🎭 Here's what I think matches your mood:",

	"btn_profile":             "👤 My Profile",
	"btn_add_favorite":        "⭐ Add to Favorites",
	"btn_remove_favorite":     "💔 Remove from Favorites",
	"btn_mark_watching":       "▶️ Mark as Watching",
	"btn_watching_active":     "▶️ Watching ✅",
	"btn_mark_completed":      "🏁 Mark as Completed",
	"btn_completed_active":    "🏁 Completed ✅",
	"favorite_added":          "⭐ Added to Favorites!",
	"favorite_removed":        "💔 Removed from Favorites.",
	"watch_status_watching":   "▶️ Got it, marked as watching!",
	"watch_status_completed":  "🏁 Nice, marked as completed!",
	"btn_my_favorites":        "⭐ My Favorites",
	"btn_my_watching":         "▶️ Currently Watching",
	"btn_my_recent":           "🕒 Recently Viewed",
	"profile_text":            "👤 *Your Profile*\n\n🌐 Language: %s\n📅 Member since: %s\n\n⭐ Favorites: %d\n▶️ Watching: %d\n🏁 Completed: %d\n📺 Total episodes watched: %d\n🏷 Favorite genres: %s",
	"profile_no_genres":       "not enough data yet",
	"profile_favorites_empty": "😔 You haven't added anything to Favorites yet. Tap the ⭐ button under any anime!",
	"profile_favorites_title": "⭐ Your Favorites:",
	"profile_watching_empty":  "😔 You're not watching anything right now.",
	"profile_watching_title":  "▶️ Here's what you're watching:",
	"profile_recent_empty":    "😔 You haven't viewed anything yet.",
	"profile_recent_title":    "🕒 Here's what you viewed recently:",
}
