package api

// EnglishMessages сатрҳои интерфейс барои забони англисӣ
var EnglishMessages = map[string]string{
	"welcome":                     "👋 Welcome to *App Builder Bot*!\n\nPlease choose your language:",
	"welcome_back":                "👋 Welcome back, %s!\n\nBuilding an app?",
	"language_set":                "✅ Language set to English!",
	"main_menu":                   "What would you like to do?",
	"btn_search":                  "🔍 Search Anime",
	"btn_random":                  "🎲 Random Anime",
	"btn_mood":                    "🎭 Suggest by Mood",
	"btn_top":                     "🏆 Top Anime",
	"btn_settings":                "⚙️ Settings",
	"btn_help":                    "❓ Help",
	"ask_search_query":            "🔍 Send me the anime name you want to search for:",
	"searching":                   "🔎 Searching for \"%s\"...",
	"no_results":                  "😔 No anime found for \"%s\". Try another name.",
	"search_results":              "🔍 Results for \"%s\":",
	"loading_anime":               "⏳ Loading anime details...",
	"anime_not_found":             "😔 Anime not found.",
	"episodes_title":              "📺 Episodes for *%s*",
	"no_episodes":                 "No episode data available yet.",
	"episode_line_label":          "Episode %d",
	"episode_filler_tag":          "[filler]",
	"episode_recap_tag":           "[recap]",
	"btn_episodes":                "📺 Episodes",
	"btn_open_mal":                "🔗 Open on MyAnimeList",
	"btn_back":                    "⬅️ Back",
	"choose_season":               "📺 *%s* — which season?",
	"season_title":                "📺 Season %d — *%s*",
	"btn_all_seasons":             "🗂 All Seasons",
	"btn_back_to_menu":            "⬅️ Back to menu",
	"settings_title":              "⚙️ *Settings*\n\nCurrent language: %s",
	"btn_change_lang":             "🌐 Change Language",
	"help_text":                   "🤖 *What I can do:*\n\n🏗 *App Builder* — send the app name, I'll create a repo on the bot owner's GitHub with a ready-made APK build workflow.\n\n📦 *Fetch APK* — once you've pushed your code and GitHub Actions built it, send the repo name — I'll send the APK.\n\nCommands:\n/start - restart the bot\n/settings - change language\n/help - show this message",
	"error_generic":               "⚠️ Something went wrong. Please try again later.",
	"subscription_required":       "📢 To use this bot, please subscribe to these channels first, then tap \"✅ Check\":",
	"btn_check_subscription":      "✅ Check",
	"subscription_confirmed":      "✅ Great! You're subscribed to everything. Send /start to begin.",
	"subscription_still_missing":  "😔 You haven't subscribed to all channels yet. Subscribe first, then check again.",
	"subscription_required_short": "📢 Please subscribe to the required channels first!",
	"score_label":                 "⭐ Score",
	"episodes_label":              "📺 Episodes",
	"status_label":                "📌 Status",
	"type_label":                  "🎞 Type",
	"year_label":                  "📅 Year",
	"genres_label":                "🏷 Genres",
	"top_title":                   "🏆 Top Anime Right Now",
	"random_loading":              "🎲 Picking a random anime for you...",
	"ask_mood":                    "🎭 Tell me what mood you're in — e.g. \"romance\", \"funny\", \"scary\", \"action\", \"sad\"... write it in your own words, I'll figure it out 😉",
	"mood_searching":              "🎭 Looking for something that fits your mood...",
	"mood_result_intro":           "🎭 Here's what I think matches your mood:",

	"btn_profile":             "👤 My Profile",
	"btn_add_favorite":        "⭐ Add to Favorites",
	"btn_remove_favorite":     "💔 Remove from Favorites",
	"btn_mark_watching":       "▶️ Mark as Watching",
	"btn_watching_active":     "▶️ Watching ✅",
	"btn_mark_completed":      "🏁 Mark as Completed",
	"btn_completed_active":    "🏁 Completed ✅",
	"favorite_added":          "⭐ Added to Favorites!",
	"favorite_removed":        "💔 Removed from Favorites.",
	"watch_status_watching":   "▶️ Got it, marked as watching!",
	"watch_status_completed":  "🏁 Nice, marked as completed!",
	"btn_my_favorites":        "⭐ My Favorites",
	"btn_my_watching":         "▶️ Currently Watching",
	"btn_my_recent":           "🕒 Recently Viewed",
	"profile_text":            "👤 *Your Profile*\n\n🌐 Language: %s\n📅 Member since: %s\n\n⭐ Favorites: %d\n▶️ Watching: %d\n🏁 Completed: %d\n📺 Total episodes watched: %d\n🏷 Favorite genres: %s",
	"profile_no_genres":       "not enough data yet",
	"profile_favorites_empty": "😔 You haven't added anything to Favorites yet. Tap the ⭐ button under any anime!",
	"profile_favorites_title": "⭐ Your Favorites:",
	"profile_watching_empty":  "😔 You're not watching anything right now.",
	"profile_watching_title":  "▶️ Here's what you're watching:",
	"profile_recent_empty":    "😔 You haven't viewed anything yet.",
	"profile_recent_title":    "🕒 Here's what you viewed recently:",

	"btn_find_dub":                  "🎬 Find Dub",
	"btn_dub_menu":                  "🎬 Find Dub",
	"ask_dub_query":                 "🎬 Type the anime name, I'll search several video platforms for a dubbed version:",
	"dub_searching":                 "🎬 Searching for a matching dub...",
	"dub_no_results":                "😔 Couldn't find a dub for this anime. Maybe try a different title?",
	"dub_results_title":             "🎬 Found these:",
	"btn_find_dub_season":           "🎬 Dub for this Season",
	"dub_season_fallback":           "😔 Couldn't find dubs matching this season's exact episode order. Here's what I found, it might be in there:",
	"dub_season_searching":          "🎬 Searching for each episode of this season individually — this can take up to a minute, hang on...",
	"dub_season_found_count":        "🎬 Found %d out of %d episodes:",
	"btn_check_filimo":              "🎬 Check on Filimo",
	"btn_feedback":                  "💬 Contact Admin",
	"ask_feedback":                  "💬 I'm listening — write your question, complaint, suggestion, or feedback about the bot. I'll send it straight to the admin:",
	"feedback_sent":                 "✅ Sent! The admin will see it and may reply here.",
	"admin_reply_prefix":            "💬 Admin's reply:",
	"feedback_admin_not_configured": "⚠️ This feature isn't set up yet (ADMIN_CHAT_ID missing). If you're the bot owner, send /myid to get your ID.",

	"btn_tools":             "🛠 Tools",
	"tools_menu_title":      "🛠 Handy tools — which one do you need?",
	"btn_password_gen":      "🔐 Password Generator",
	"btn_qr_gen":            "📷 QR Generator",
	"btn_currency":          "💱 Currency Converter",
	"password_result":       "🔐 New strong password:\n`%s`",
	"ask_qr_text":           "📷 Send text or a link, I'll turn it into a QR code:",
	"ask_currency_text":     "💱 Type in this format: AMOUNT FROM TO (e.g. 100 USD EUR):",
	"currency_format_error": "😔 Wrong format. Example: 100 USD EUR",
	"currency_result":       "💱 %.2f %s = %.2f %s",
	"currency_error":        "😔 Couldn't find that rate. Check the currency code (e.g. USD, EUR, RUB).",

	"btn_worldcup":        "⚽ World Cup 2026",
	"worldcup_loading":    "⚽ Looking up matches...",
	"worldcup_title":      "⚽ World Cup 2026 matches:",
	"worldcup_no_matches": "😔 No nearby matches found right now.",
	"worldcup_error":      "⚠️ Couldn't fetch results. Try again later.",

	"btn_app_builder":              "🏗 App Builder",
	"btn_fetch_apk":                "📦 Fetch APK",
	"ask_app_name":                 "🏗 Describe what the app should be (e.g. \"social app with profile, messages, search\") — I'll create a repo on your GitHub and (if AI is enabled) generate a first screen with 5 functions:",
	"appbuilder_creating":          "🏗 Creating the repo...",
	"appbuilder_generating_screen": "🎨 Generating the app screen with AI...",
	"appbuilder_ai_error":          "⚠️ Repo created, but the AI screen generation failed (maybe a bad OpenRouter token or an AI error). The repo is empty — you can push your own code.",
	"appbuilder_created":           "✅ Done!\n\nRepo: `%s`\nLink: %s\n\nIf the AI screen was generated, the repo is already ready to build — just tap \"📦 Fetch APK\" in a couple minutes. If not, push your own code.",
	"appbuilder_error":             "😔 Failed to create the repo. Maybe the name already exists or the token is wrong — check it.",
	"appbuilder_not_configured":    "⚠️ This feature isn't set up (GITHUB_APP_BUILDER_TOKEN missing).",
	"ask_apk_repo":                 "📦 Send the repo name (e.g. \"my-app\" or \"owner/my-app\"):",
	"apk_fetching":                 "📦 Looking for the latest APK...",
	"apk_not_found":                "😔 No finished APK found. The build may not be done yet, or no code has been pushed.",
}
