package api

// RussianMessages сатрҳои интерфейс барои забони русӣ
var RussianMessages = map[string]string{
	"welcome":                     "👋 Добро пожаловать в *AnimeBot*!\n\nВыберите язык:",
	"welcome_back":                "👋 С возвращением, %s!\n\nЧто хотите сделать?",
	"language_set":                "✅ Язык изменён на русский!",
	"main_menu":                   "Что хотите сделать?",
	"btn_search":                  "🔍 Поиск аниме",
	"btn_random":                  "🎲 Случайное аниме",
	"btn_mood":                    "🎭 Подобрать по настроению",
	"btn_top":                     "🏆 Топ аниме",
	"btn_settings":                "⚙️ Настройки",
	"btn_help":                    "❓ Помощь",
	"ask_search_query":            "🔍 Отправьте название аниме для поиска:",
	"searching":                   "🔎 Ищу \"%s\"...",
	"no_results":                  "😔 Аниме \"%s\" не найдено. Попробуйте другое название.",
	"search_results":              "🔍 Результаты для \"%s\":",
	"loading_anime":               "⏳ Загружаю информацию об аниме...",
	"anime_not_found":             "😔 Аниме не найдено.",
	"episodes_title":              "📺 Эпизоды *%s*",
	"no_episodes":                 "Информация об эпизодах пока недоступна.",
	"episode_line_label":          "Серия %d",
	"episode_filler_tag":          "[филлер]",
	"episode_recap_tag":           "[повтор]",
	"btn_episodes":                "📺 Эпизоды",
	"btn_open_mal":                "🔗 Открыть на MyAnimeList",
	"btn_back":                    "⬅️ Назад",
	"choose_season":               "📺 *%s* — какой сезон?",
	"season_title":                "📺 Сезон %d — *%s*",
	"btn_all_seasons":             "🗂 Все сезоны",
	"btn_back_to_menu":            "⬅️ В меню",
	"settings_title":              "⚙️ *Настройки*\n\nТекущий язык: %s",
	"btn_change_lang":             "🌐 Сменить язык",
	"help_text":                   "🤖 *Помощь AnimeBot*\n\nОтправьте название аниме для поиска или используйте кнопки меню.\n\nКоманды:\n/start - перезапустить бота\n/search <название> - поиск аниме\n/random - случайное аниме\n/top - топ аниме\n/settings - изменить язык\n/help - показать это сообщение",
	"error_generic":               "⚠️ Что-то пошло не так. Попробуйте позже.",
	"subscription_required":       "📢 Чтобы пользоваться ботом, сначала подпишись на эти каналы, потом нажми \"✅ Проверить\":",
	"btn_check_subscription":      "✅ Проверить",
	"subscription_confirmed":      "✅ Отлично! Ты подписан на всё. Отправь /start, чтобы начать.",
	"subscription_still_missing":  "😔 Ты подписался ещё не на всё. Сначала подпишись, потом проверь снова.",
	"subscription_required_short": "📢 Сначала подпишись на нужные каналы!",
	"score_label":                 "⭐ Рейтинг",
	"episodes_label":              "📺 Эпизоды",
	"status_label":                "📌 Статус",
	"type_label":                  "🎞 Тип",
	"year_label":                  "📅 Год",
	"genres_label":                "🏷 Жанры",
	"top_title":                   "🏆 Топ аниме сейчас",
	"random_loading":              "🎲 Подбираю случайное аниме...",
	"ask_mood":                    "🎭 Расскажи, какое у тебя настроение — например: \"романтика\", \"смешное\", \"страшное\", \"экшн\", \"грустное\"... пиши как удобно, я разберусь 😉",
	"mood_searching":              "🎭 Ищу что-нибудь подходящее под твоё настроение...",
	"mood_result_intro":           "🎭 Вот что, кажется, подойдёт под твоё настроение:",

	"btn_profile":             "👤 Мой профиль",
	"btn_add_favorite":        "⭐ В избранное",
	"btn_remove_favorite":     "💔 Убрать из избранного",
	"btn_mark_watching":       "▶️ Смотрю сейчас",
	"btn_watching_active":     "▶️ Смотрю ✅",
	"btn_mark_completed":      "🏁 Просмотрено",
	"btn_completed_active":    "🏁 Просмотрено ✅",
	"favorite_added":          "⭐ Добавлено в избранное!",
	"favorite_removed":        "💔 Убрано из избранного.",
	"watch_status_watching":   "▶️ Отметил, что ты это смотришь!",
	"watch_status_completed":  "🏁 Отлично, отметил как просмотренное!",
	"btn_my_favorites":        "⭐ Моё избранное",
	"btn_my_watching":         "▶️ Смотрю сейчас",
	"btn_my_recent":           "🕒 Недавно просмотренное",
	"profile_text":            "👤 *Твой профиль*\n\n🌐 Язык: %s\n📅 С нами с: %s\n\n⭐ Избранное: %d\n▶️ Смотрю: %d\n🏁 Просмотрено: %d\n📺 Всего эпизодов просмотрено: %d\n🏷 Любимые жанры: %s",
	"profile_no_genres":       "пока данных мало",
	"profile_favorites_empty": "😔 Ты ещё ничего не добавил в избранное. Нажми ⭐ под любым аниме!",
	"profile_favorites_title": "⭐ Твоё избранное:",
	"profile_watching_empty":  "😔 Сейчас ты ничего не смотришь.",
	"profile_watching_title":  "▶️ Вот что ты сейчас смотришь:",
	"profile_recent_empty":    "😔 Ты ещё ничего не смотрел.",
	"profile_recent_title":    "🕒 Вот что ты недавно смотрел:",

	"btn_find_dub":                  "🎬 Найти озвучку",
	"btn_dub_menu":                  "🎬 Найти озвучку",
	"ask_dub_query":                 "🎬 Напиши название аниме, я поищу озвучку на нескольких видеоплатформах:",
	"dub_searching":                 "🎬 Ищу подходящую озвучку...",
	"dub_no_results":                "😔 Не удалось найти озвучку этого аниме. Попробуй другое название?",
	"dub_results_title":             "🎬 Вот что нашлось:",
	"btn_find_dub_season":           "🎬 Озвучка этого сезона",
	"dub_season_fallback":           "😔 Не удалось найти озвучку именно в порядке серий этого сезона. Вот что нашлось, может быть среди этого:",
	"dub_season_searching":          "🎬 Ищу каждую серию этого сезона по отдельности — это может занять до минуты, подожди...",
	"dub_season_found_count":        "🎬 Найдено %d из %d серий:",
	"btn_check_filimo":              "🎬 Проверить на Filimo",
	"btn_feedback":                  "💬 Написать админу",
	"ask_feedback":                  "💬 Слушаю — напиши свой вопрос, жалобу, предложение или отзыв о боте. Отправлю прямо админу:",
	"feedback_sent":                 "✅ Отправлено! Админ увидит и может ответить здесь же.",
	"admin_reply_prefix":            "💬 Ответ админа:",
	"feedback_admin_not_configured": "⚠️ Эта функция ещё не настроена (не задан ADMIN_CHAT_ID). Если ты владелец бота, отправь /myid, чтобы узнать свой ID.",

	"btn_tools":             "🛠 Инструменты",
	"tools_menu_title":      "🛠 Полезные инструменты — что нужно?",
	"btn_password_gen":      "🔐 Генератор паролей",
	"btn_qr_gen":            "📷 Генератор QR-кодов",
	"btn_currency":          "💱 Конвертер валют",
	"password_result":       "🔐 Новый надёжный пароль:\n`%s`",
	"ask_qr_text":           "📷 Напиши текст или ссылку, я сделаю QR-код:",
	"ask_currency_text":     "💱 Напиши в формате: СУММА ИЗ В (например: 100 USD EUR):",
	"currency_format_error": "😔 Неверный формат. Пример: 100 USD EUR",
	"currency_result":       "💱 %.2f %s = %.2f %s",
	"currency_error":        "😔 Не удалось найти курс. Проверь код валюты (например USD, EUR, RUB).",

	"btn_worldcup":        "⚽ Чемпионат мира 2026",
	"worldcup_loading":    "⚽ Ищу матчи...",
	"worldcup_title":      "⚽ Матчи Чемпионата мира 2026:",
	"worldcup_no_matches": "😔 Сейчас ближайших матчей не найдено.",
	"worldcup_error":      "⚠️ Не удалось получить результаты. Попробуй позже.",
}
